/*******************************************************************************
* FILENAME: project.h
* 
* PSoC Creator  3.2
*
* DESCRIPTION:
* It contains references to all generated header files and should not be modified.
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2015 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#include "cyfitter_cfg.h"
#include "cydevice_trm.h"
#include "cyfitter.h"
#include "cydisabledsheets.h"
#include "ADC.h"
#include "Pin_Sensor_3.h"
#include "Pin_Sensor_3_aliases.h"
#include "Pin_Sensor_4.h"
#include "Pin_Sensor_4_aliases.h"
#include "UART.h"
#include "UART_SPI_UART.h"
#include "UART_PINS.h"
#include "UART_SPI_UART_PVT.h"
#include "UART_PVT.h"
#include "UART_BOOT.h"
#include "Pin_Sensor_1.h"
#include "Pin_Sensor_1_aliases.h"
#include "Pin_Sensor_2.h"
#include "Pin_Sensor_2_aliases.h"
#include "TDOA.h"
#include "Pin_Debug1.h"
#include "Pin_Debug1_aliases.h"
#include "Pin_Debug4.h"
#include "Pin_Debug4_aliases.h"
#include "Pin_Debug3.h"
#include "Pin_Debug3_aliases.h"
#include "Pin_Debug2.h"
#include "Pin_Debug2_aliases.h"
#include "ADC_IRQ.h"
#include "ADC_intClock.h"
#include "UART_SCBCLK.h"
#include "UART_tx.h"
#include "UART_tx_aliases.h"
#include "UART_rx.h"
#include "UART_rx_aliases.h"
#include "core_cm0_psoc4.h"
#include "core_cm0.h"
#include "CyFlash.h"
#include "CyLib.h"
#include "cyPm.h"
#include "cytypes.h"
#include "cypins.h"
#include "core_cmFunc.h"
#include "core_cmInstr.h"
#include "CyDMA.h"
#include "CyLFClk.h"

/*[]*/

